### ISSUE TITLE
TK.133 Come si crea un componente in Angular

### ISSUE THREAD

**Issue by francescosave** [TeleCO2gram/frontend#4]

**Comment by marghe27** [comment]
Per creare un nuovo componente, esegui il comando: `ng generate component nome-componente`.
Questo comando crea quattro file:
1. nome-componente.component.ts: contiene la logica del componente;
2. nome-componente.component.html: contiene il template HTML del componente;
3. nome-componente.component.css: contiene gli stili CSS del componente;
4. nome-componente.component.spec.ts: contiene i test per il componente (opzionale).

- Il **Template HTML** contiene i tag html: `<h1>Ciao, sono il nuovo componente!</h1>`;

- La **Logica del Componente** invece ha il seguente contenuto: 

```
`import { Component } from '@angular/core';

@Component({
  selector: 'app-nome-componente',
  templateUrl: './nome-componente.component.html',
  styleUrls: ['./nome-componente.component.css']
})
export class NomeComponenteComponent {
  // Qui va la logica del componente
}`
```
